# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-06 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=36, unique=True)),
                ('job_label', models.CharField(max_length=128)),
                ('pid', models.SmallIntegerField(default=-1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('progress', models.SmallIntegerField(default=-1)),
                ('exit_status', models.SmallIntegerField()),
                ('exit_output', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
