# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-02 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_job_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjob',
            name='exit_status',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='pid',
            field=models.SmallIntegerField(null=True),
        ),
    ]
