# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_job_client', '0002_auto_20181002_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjob',
            name='progress',
            field=models.SmallIntegerField(null=True),
        ),
    ]
